### PR TITLE
re-fix cythonize

### PR DESCRIPTION
**Pull request by bjlittle**
Addresses #34 (again, sorry)

Closes #98

### CODE REVIEW

**Comment by bjlittle** [comment]
The coverage is back to ~87%, which is what we expect... and the `setup.py` will only `cythonize` if `Cython` is available (and it is for the travis-ci test environment, hence the coverage works correctly), otherwise `setup.py` won't `cythonize` the `Extension`, as per previously.

**Comment by jswhit** [comment]
Hopefully it still will cythonize the extension even if cython is not installed, since cython is in setup_requires.  (that was the source of the problem reported in issue #34)   What is cythonize doing that distutils Extension doesn't to enable the coverage stuff to work?  Is it not using the `compiler_directives` and `language_level` kwargs?

**Comment by jswhit** [comment]
Agreed.  I'll see if I can test in an environment without cython installed, just to make sure it works as expected.

**Comment by jswhit** [comment]
Works as expect in a environment without cython, merging now....

**Comment by bjlittle** [comment]
Thanks @jswhit and apologies for the carnage...

**Pull request merged**
