### PR TITLE
address issue #248

### PR DESCRIPTION
**Pull request by jswhit**
This PR changes the behavior of cftime.datetime initialization.  Previously, specifying year=0 without the has_year_zero kwarg will raise an exception if the default  for that calendar is has_year_zero=False.  With this change specifying year=0 without a has_year_zero kwarg will cause has_year_zero to be set to True. 

The assumption here is that if the user is asking for an instance for year=0, they implicitly want the version of the calendar that includes year zero.

@spencerkclark would appreciate it if you would take a look at this and make sure it doesn't break xarray

### CODE REVIEW

**Comment by jswhit** [comment]
@bjlittle and @spencerkclark - if you have a chance your feedback would be welcome.  I plan to merge later next week.

**Comment by spencerkclark** [comment]
Thanks for the ping @jswhit.  I believe everything in xarray would still work with this change.  That said, from a user experience perspective, if this change is adopted we might move toward explicitly specifying our year-zero conventions anywhere where we construct dates manually in the code.  I prefer that the error message continues to come immediately from specifying a date with an inconsistent convention rather than something downstream, since in xarray we assume the CF conventions are followed.

I see @bjlittle's point regarding if a user specifies year zero then they would likely want year zero, but at the same time I do find it a little awkward that one can effectively create two different date types with the same constructor:
```
>>> import cftime
>>> a = cftime.DatetimeGregorian(0, 1, 1)
>>> b = cftime.DatetimeGregorian(1, 1, 1)
>>> b - a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cftime/_cftime.pyx", line 1398, in cftime._cftime.datetime.__sub__
TypeError: cannot compute the time difference between dates with year zero conventions
```

**Comment by jswhit** [comment]
Perhaps a warning should be raised when year zero is requested and the default has_year_zero kwarg would otherwise be False, so that the user is aware they are creating an instance that doesn't conform to CF standards/

**Comment by spencerkclark** [comment]
I like the idea of including a warning.  That would be a good compromise.

**Comment by jswhit** [comment]
@bjlittle I'd still like to have you look this over to make sure it addresses your original issue.  I'll go ahead and merge if I don't hear from you by this Friday (Aug 13).

**Pull request merged**
