### PR TITLE
add isformat method (issue #152)

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by jswhit** [comment]
Should the default separator be ' ' for backwards compatibility, or 'T' for compatibility with python datetime?

**Comment by dopplershift** [comment]
Awesome, thanks for taking it on!

Backward compatibility with...?  I'm confused since this method didn't exist here. Wikipedia's page on [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) indicates that you can't use a space as a separator. (Under Combined Date and Time Representations).

**Comment by jswhit** [comment]
The `__str__` method now uses `isoformat`.  printing an instance now uses a blank for a separator.  I suppose I can keep that, but make the default for isoformat 'T' as in python datetime.

**Comment by dopplershift** [comment]
That seems like a reasonable way to structure it. I hadn't caught the change to `__str__`.

**Pull request merged**
