### PR TITLE
Make cftime.datetime - cftime.datetime -> timedelta microsecond-exact

### PR DESCRIPTION
**Pull request by spencerkclark**
Currently subtracting a date from another to produce a timedelta is not microsecond-exact:

```
In [1]: import cftime

In [2]: cftime.DatetimeNoLeap(2000, 1, 2, 0, 0, 0, 5) - cftime.DatetimeNoLeap(2000, 1, 2)
Out[2]: datetime.timedelta(microseconds=8)
```

I think this is actually pretty straightforward to fix using some code that already exists in cftime.  I'm drawing inspiration here from [the way this kind of operation is done in Python's datetime object](https://github.com/python/cpython/blob/a4c09560eaa1e3b9733c7e63d570b6fa7626724c/Lib/datetime.py#L2084-L2097).  As I understand it, we can simply use `_IntJulianDayFromDate` as something essentially equivalent to `datetime.datetime.toordinal`, and everything else should basically be the same.

The test confirms the example above is fixed for all calendars, and all other existing tests of timedelta arithmetic pass.  @jswhit I think this should enable the exact version of `date2num` you described in https://github.com/Unidata/cftime/issues/171#issuecomment-636201592.  I could try to add that here or in another PR.  As you note, it would be awesome to be able to round-trip dates without loss of precision.

xref: #109 (this would make the function described there no longer necessary)

### CODE REVIEW

**Comment by jswhit** [comment]
Wow - very simple and elegant solution!   I can merge once you resolve the conflicts.

**Comment by spencerkclark** [comment]
Thanks @jswhit -- indeed I was pleasantly surprised to find that I could reuse the `_IntJulianDayFromDate` function, which was already so nicely implemented for the original version of the calculation!  

Merge conflicts have been resolved; I think things should be ready to go.

**Comment by jswhit** [comment]
Merging now.  I will wait a week or so and then push another release.

**Comment by jswhit** [comment]
Also, it would be good to run the xarray test suite to make sure this has not broken anything before a new release

**Comment by spencerkclark** [comment]
> Oops - we forgot the Changelog entry.

Ah yes, thanks for reminding me -- see #179.

> Also, it would be good to run the xarray test suite to make sure this has not broken anything before a new release

Yes, I've confirmed that the xarray test suite passes with the latest updates.  I'm looking forward to eventually being able to remove some of the tolerance logic we have in our cftime round-tripping tests (we'll still support older versions of cftime for some time).

**Pull request merged**
